######################################
# Configuration for individual methods
######################################
2020+:
    qvalue:
        - oncogene q-value
        - tsg q-value
        - driver q-value
    pvalue:
        - driver p-value
    threshold:
        score: 0.1
        top: low
